# Generated by Django 6.0.2 on 2026-03-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default='unknown', max_length=15),
        ),
    ]
