# Generated by Django 6.0.2 on 2026-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="work_update",
            field=models.TextField(blank=True, default=""),
        ),
    ]
